// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnT_Yom1XA_MhNPRxm2HctZ2913Fb3mho',
    appId: '1:985266439475:web:e902e7d7fe2b910dec6a46',
    messagingSenderId: '985266439475',
    projectId: 'firstproject-2423b',
    authDomain: 'firstproject-2423b.firebaseapp.com',
    storageBucket: 'firstproject-2423b.firebasestorage.app',
    measurementId: 'G-LWT8LFNKP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFxidqDX_0Dm9JgpErWqBEicghxOUOeI',
    appId: '1:985266439475:android:00ad9f73e6ccc3a9ec6a46',
    messagingSenderId: '985266439475',
    projectId: 'firstproject-2423b',
    storageBucket: 'firstproject-2423b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtSx4nwD33vWNftwWyrrsGmS-EUpHxqno',
    appId: '1:985266439475:ios:e02422ab17e5bdedec6a46',
    messagingSenderId: '985266439475',
    projectId: 'firstproject-2423b',
    storageBucket: 'firstproject-2423b.firebasestorage.app',
    iosBundleId: 'com.example.np',
  );
}
